import { NextRequest, NextResponse } from "next/server";
import { z } from "zod";
import { TRANSITFLOW_SYSTEM_PROMPT } from "@/features/chat/system-prompt";
import { getSimulatedSpatialResponse } from "@/features/chat/fallback-service";

const chatRequestSchema = z.object({
  messages: z
    .array(
      z.object({
        role: z.enum(["user", "assistant", "system"]),
        content: z.string().min(1, "Message content cannot be empty").max(4000),
      })
    )
    .min(1, "At least one message is required"),
  temperature: z.number().min(0).max(2).optional().default(0.7),
  max_tokens: z.number().min(100).max(2048).optional().default(800),
});

export async function POST(req: NextRequest) {
  try {
    const rawBody = await req.json();
    const parseResult = chatRequestSchema.safeParse(rawBody);

    if (!parseResult.success) {
      return NextResponse.json(
        {
          status: "error",
          message: "Invalid request payload",
          errors: parseResult.error.flatten(),
        },
        { status: 400 }
      );
    }

    const { messages, temperature, max_tokens } = parseResult.data;
    const lastUserMessage =
      [...messages].reverse().find((m) => m.role === "user")?.content || "";

    // 1. Hard Deadline Killswitch Check (defaults to Sept 25, 2026 00:00:00 WIB)
    const expiryDateStr =
      process.env.COMMANDCODE_EXPIRY_DATE || "2026-09-25T00:00:00+07:00";
    const expiryTimestamp = new Date(expiryDateStr).getTime();

    if (Date.now() >= expiryTimestamp) {
      return NextResponse.json({
        role: "assistant",
        content: `> **🛡️ Security Guardrail Active**: The CommandCode API key expired on **September 25, 2026** as scheduled to prevent post-competition billing and quota abuse. TransitFlow has automatically transitioned to the deterministic Spatial Copilot simulation engine.\n\n${getSimulatedSpatialResponse(
          lastUserMessage
        )}`,
        reasoning: "Execution halted by date guardrail (>= 2026-09-25T00:00:00+07:00). Falling back to offline spatial simulation.",
        model: "deepseek/deepseek-v4.1-flash [EXPIRED]",
        offline: true,
        expired: true,
      });
    }

    // 2. Check API Key
    const apiKey = process.env.COMMANDCODE_API_KEY;
    const model =
      process.env.COMMANDCODE_MODEL || "deepseek/deepseek-v4.1-flash";

    if (!apiKey || apiKey === "your_commandcode_api_key_here") {
      return NextResponse.json({
        role: "assistant",
        content: `> **ℹ️ Offline Mode**: \`COMMANDCODE_API_KEY\` is not configured. Serving from TransitFlow Spatial Intelligence simulation.\n\n${getSimulatedSpatialResponse(
          lastUserMessage
        )}`,
        model: "transitflow-offline-copilot",
        offline: true,
        expired: false,
      });
    }

    // 3. Make outbound request to CommandCode Provider API
    const commandCodeUrl =
      "https://api.commandcode.ai/provider/v1/chat/completions";

    const outgoingMessages = [
      { role: "system", content: TRANSITFLOW_SYSTEM_PROMPT },
      ...messages.map((m) => ({
        role: m.role,
        content: m.content,
      })),
    ];

    const response = await fetch(commandCodeUrl, {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        Authorization: `Bearer ${apiKey}`,
      },
      body: JSON.stringify({
        model,
        messages: outgoingMessages,
        max_tokens,
        temperature,
      }),
    });

    if (!response.ok) {
      const errorText = await response.text().catch(() => "");
      console.error(
        `CommandCode API error (${response.status}):`,
        errorText
      );

      return NextResponse.json({
        role: "assistant",
        content: `> **⚠️ Notice**: CommandCode upstream returned status ${response.status}. Serving intelligent spatial fallback.\n\n${getSimulatedSpatialResponse(
          lastUserMessage
        )}`,
        model,
        offline: true,
        expired: false,
      });
    }

    const data = await response.json();
    const choice = data?.choices?.[0];
    const message = choice?.message;
    const content = message?.content || "No response generated by model.";
    const reasoning = message?.reasoning || undefined;

    return NextResponse.json({
      role: "assistant",
      content,
      reasoning,
      model: data?.model || model,
      offline: false,
      expired: false,
    });
  } catch (error) {
    console.error("Chat API route unexpected error:", error);
    return NextResponse.json(
      {
        status: "error",
        message:
          error instanceof Error ? error.message : "Internal Server Error",
      },
      { status: 500 }
    );
  }
}
